name: Unit Tests
description: Perform ansible-test units

inputs:
  python-version:
    required: true
    type: string
  collection:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ inputs.python-version }}"

      - name: Install ansible-core
        shell: bash
        run: pip install ansible-core

      - name: Setup ansible_collections
        shell: bash
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/opengear
          cp -r opengear/${{ inputs.collection }} ~/.ansible/collections/ansible_collections/opengear
          find ~/.ansible/collections/ansible_collections/opengear/${{ inputs.collection }}/tests -type d

      - name: Run unit tests
        shell: bash
        run: |
          cd ~/.ansible/collections/ansible_collections/opengear/${{ inputs.collection }}
          ansible-test units --docker --requirements --python ${{ inputs.python-version }}
