namespace: opengear
name: ng
version: 1.0.0
readme: README.md
authors:
  - Opengear <software@opengear.com>
description: Ansible modules for managing Opengear console servers and out-of-band management devices.
license:
  - GPL-3.0-or-later
tags: [opengear, ng, restapi, networking, automation]
dependencies:
  "ansible.netcommon": ">=8.1.0"
repository: https://github.com/opengear/ansible-ng
documentation: https://github.com/opengear/ansible-ng
homepage: https://github.com/opengear/ansible-ng
issues: https://github.com/opengear/ansible-ng/issues

build_ignore:
  - tests/
