---
- name: Example playbook for managing groups
  hosts: opengear
  gather_facts: false

  tasks:
    - name: Gather groups facts
      opengear.ng.facts:
        gather_network_resources:
          - groups
      register: facts_result

    - name: Show current groups
      debug:
        var: facts_result

    # Create a new group, the new group is merged with current groups config
    - name: Create operators group
      opengear.ng.groups:
        config:
          - groupname: operators
            description: Regular operator access [Managed by Ansible]
            enabled: true
            access_rights:
              - web_ui
              - pmshell
            ports:
              - ports-1
              - ports-2
              - ports-5
        state: merged
      register: group_result

    - name: Show current group
      debug:
        var: group_result

    # Modify the group to add an extra port, merged with current groups config
    - name: Increase scope of operators group (merge)
      opengear.ng.groups:
        config:
          - groupname: operators
            ports:
              - ports-6
        state: merged
      register: group_result

    - name: Show current group
      debug:
        var: group_result

    # Reduce the access of the group, set expected state with replace.
    - name: Reduce access for operators group
      opengear.ng.groups:
        config:
          - groupname: operators
            description: Regular operator access [Managed by Ansible]
            enabled: true
            access_rights:
              - web_ui
              - pmshell
            ports:
              - ports-1
              - ports-2
              - ports-5
            members: []
        state: replaced
      register: group_result

    - name: Show current group
      debug:
        var: group_result

    - name: Delete operators group
      opengear.ng.groups:
        config:
          - groupname: operators
        state: deleted
      register: group_result

    - name: Show current group
      debug:
        var: group_result
