#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2021 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################


from __future__ import absolute_import, division, print_function
__metaclass__ = type


ANSIBLE_METADATA = {
    'metadata_version': '1.0',
    'status': ['preview'],
    'supported_by': 'opengear'
}

DOCUMENTATION = """
---
module: om_groups
version_added: '1.0.0'
short_description: Manages user attributes of opengear om groups
description:
  - Manages user attributes of opengear om groups
author:
  - Opengear (@opengear)
options:
  config:
    description: Retrieve and update user information
    type: list
    elements: dict
    suboptions:
      id:
        type: str
        description: group id
      groupname:
        type: str
        description: group name
      description:
        type: str
        description: A description of the group's purpose.
      enabled:
        type: bool
        description: group enabled or disabled
      access_rights:
        type: list
        elements: str
        description: List of access rights assigned to the group.
      members:
        type: list
        elements: str
        description: List of user ids or usernames that are members of the group.
      ports:
        type: list
        description: List of port ids assigned to the group.
        elements: str
      mode:
        type: str
        description: Group mode. Deprecated since 2022/08, use C(access_rights) instead.
      role:
        type: str
        description: Group role. Deprecated since 2022/08, use C(access_rights) instead.
  state:
    description:
    - The state of the configuration after module completion.
    type: str
    choices:
    - merged
    - replaced
    - overridden
    - deleted
    - gathered
    - rendered
    default: merged
"""

EXAMPLES = """
- name: Configure groups
  opengear.om.om_groups:
    config:
      - groupname: netops
        description: Network operations group
        enabled: true
        access_rights:
          - admin
      - groupname: readonly
        description: Read only group
        enabled: true
        access_rights:
          - web_ui
          - pmshell
        ports:
          - ports-1
          - ports-2
    state: merged

- name: Delete a group
  opengear.om.om_groups:
    config:
      - groupname: readonly
    state: deleted

- name: Gather group facts
  opengear.om.om_facts:
    gather_network_resources:
      - groups
"""

RETURN = """
before:
  description: The configuration before the module is executed.
  returned: always
  type: dict
after:
  description: The configuration after the module is executed.
  returned: when changed
  type: dict
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
"""

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.opengear.om.plugins.module_utils.network.om.argspec.groups.groups import GroupsArgs
from ansible_collections.opengear.om.plugins.module_utils.network.om.config.groups.groups import Groups


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=GroupsArgs.argument_spec,
                           supports_check_mode=True)

    result = Groups(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
