name: Lint
description: Perform ansible lint

inputs:
  python-version:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install ansible
        shell: bash
        run: pip install ansible-core ansible-lint

      - name: Install collection
        shell: bash
        run: ansible-galaxy collection install . --force

      - name: Lint opengear.ng
        shell: bash
        run: ansible-lint .
